# Generated by Django 4.0.4 on 2022-05-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_spareparts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='name3',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
