# Generated by Django 4.0.4 on 2022-05-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_spareparts', '0003_rename_name3_stocks_part_number_remove_stocks_name2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='part_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
