# Generated by Django 4.0.4 on 2022-05-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_spareparts', '0008_alter_sparepart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='image_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
