# Generated by Django 4.0.4 on 2022-05-04 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_spareparts', '0009_alter_sparepart_image_alter_sparepart_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepart',
            name='image_url',
        ),
    ]
