# Generated by Django 4.0.4 on 2022-05-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_spareparts', '0011_alter_sparepart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='qty',
            field=models.PositiveIntegerField(),
        ),
    ]
