# Generated by Django 4.0.4 on 2022-05-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_spareparts', '0013_sparepart_sub_group_alter_sparepart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='sub_group',
            field=models.CharField(choices=[('a', 'camera'), ('b', 'robot'), ('c', 'bearing'), ('d', 'controller')], max_length=1, null=True),
        ),
    ]
